jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    persistCredentials: True

  - task: oc-setup@3
    inputs:
      connectionType: 'OpenShift Connection Service'
      openshiftService: 'openshift-02'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        oc project at-rafaydev765-dev
        oc new-app https://bitbucket.org/rafay765/example-poc.git --strategy=docker --name=openshift-poc
        oc get bc openshift
        oc start-build openshift-poc-azure --from-dir=. --follow --wait


# oc apply -f k8s/live/live-deployment.yaml 
# oc apply -f k8s/live/live-service.yaml
# oc apply -f k8s/live/live-route.yaml      
# oc apply -f k8s/live/live-deployment.yaml 
# oc apply -f k8s/live/live-service.yaml 
# #  oc start-build openshift_poc_azure --from-dir=. --follow --wait
# oc new-build --binary --name openshiftpocazure --strategy=docker
# oc new-app https://github.com/MRafaydev/openshift_poc_azure