kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-poc-azure
  uid: dbcb74d3-7e76-465c-81a8-7886980558cd
  namespace: at-rafay765-dev
  labels:
    app: openshift-poc-azure
    app.kubernetes.io/component: openshift-poc-azure
    app.kubernetes.io/instance: openshift-poc-azure
    app.kubernetes.io/name: openshift-poc-azure
    app.kubernetes.io/part-of: openshift-poc-azure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-poc-azure
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openshift-poc-azure
        deployment: openshift-poc-azure
    spec:
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - loyalty-and-rewards-management
            from:
              kind: ImageStreamTag
              namespace: m11s
              name: "openshift-poc-azure"
      containers:
        - name: openshift-poc-azure
          image: >-
            image-registry.openshift-image-registry.svc:5000/at-rafay765-dev/openshift-poc-azure@sha256:2f1120d9a402f9f9b06f119ed14f1b79de341ee1f463e9b6ca870a289d1c1ba0
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: "True"
      lastUpdateTime: "2023-01-10T20:25:42Z"
      lastTransitionTime: "2023-01-10T20:25:42Z"
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: "True"
      lastUpdateTime: "2023-01-10T20:25:42Z"
      lastTransitionTime: "2023-01-10T20:24:27Z"
      reason: NewReplicaSetAvailable
      message: ReplicaSet "openshift-poc-azure-7c9fdbcfd9" has successfully progressed.
