kind: Service
apiVersion: v1
metadata:
  name: openshift-poc-azure
  namespace: at-rafay765-dev
  labels:
    app: openshift-poc-azure
    app.kubernetes.io/component: openshift-poc-azure
    app.kubernetes.io/instance: openshift-poc-azure
    app.kubernetes.io/name: openshift-poc-azure
    app.kubernetes.io/part-of: openshift-poc-azure-app
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: "https://github.com/MRafaydev/openshift_poc_azure"
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  clusterIP: 172.30.164.36
  ipFamilies:
    - IPv4
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.164.36
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: openshift-poc-azure
    deployment: openshift-poc-azure
status:
  loadBalancer: {}
